# Generated by Django 3.0.3 on 2020-04-10 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dc_main', '0004_auto_20200301_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaVkPhoto',
            fields=[
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dc_main.Media')),
                ('photo', models.IntegerField()),
                ('album', models.IntegerField()),
                ('owner', models.IntegerField()),
                ('post', models.IntegerField(blank=True)),
                ('comments', models.BooleanField(blank=True)),
                ('tags', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaVkPhotoThumbnail',
            fields=[
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dc_main.Media')),
                ('s', models.URLField(max_length=255)),
                ('m', models.URLField(blank=True, max_length=255)),
                ('x', models.URLField(blank=True, max_length=255)),
            ],
        ),
    ]
