# Generated by Django 3.1.2 on 2020-11-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_parse', '0003_auto_20200411_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('num', models.IntegerField()),
                ('action', models.CharField(max_length=20)),
                ('method', models.CharField(max_length=20)),
            ],
        ),
    ]
