# Generated by Django 3.1.2 on 2020-11-27 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dc_parse', '0004_statuploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuploads',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
