# Generated by Django 3.1.2 on 2020-12-22 20:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dc_main', '0007_auto_20200430_2032'),
        ('dc_parse', '0005_auto_20201127_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('num', models.IntegerField()),
                ('action', models.CharField(max_length=20)),
                ('method', models.CharField(max_length=20)),
                ('media', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dc_main.media')),
            ],
        ),
        migrations.DeleteModel(
            name='StatUploads',
        ),
    ]
