# Generated by Django 3.1.2 on 2020-12-22 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dc_main', '0007_auto_20200430_2032'),
        ('dc_parse', '0006_auto_20201222_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statupload',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dc_main.media'),
        ),
    ]
