# Generated by Django 3.0.3 on 2020-03-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dc_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
