# Generated by Django 3.0.3 on 2020-03-01 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dc_main', '0002_auto_20200301_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=9)),
                ('source', models.CharField(max_length=12)),
                ('url', models.URLField(max_length=255)),
                ('url_thumbnail', models.URLField(blank=True, max_length=255)),
                ('description_auto', models.TextField(blank=True)),
                ('description_me', models.TextField(blank=True)),
                ('created_date', models.DateTimeField()),
                ('when_add_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
