# Generated by Django 3.0.3 on 2020-03-01 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dc_main', '0003_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagMediaBond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dc_main.Media')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dc_main.Tag')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tagmediabond',
            constraint=models.UniqueConstraint(fields=('media', 'tag'), name='unique_bond'),
        ),
    ]
