# Generated by Django 3.0.3 on 2020-04-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_main', '0005_auto_20200418_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=90, unique=True),
        ),
    ]
