# Generated by Django 3.0.3 on 2020-04-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_main', '0006_auto_20200418_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
